### ISSUE TITLE
Anchor Tags Not Working

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#163]
Within the content pages of the Auto Accessories Guide are several anchor tags throughout. When I click on one of them, at first it works properly, dropping down to the anchor. However, after about a second, the page then reloads and brings me back to the top. This is especially apparent on the Auto Accessories Glossary page: http://www.ariesautomotive.com/page/127

**Comment by DavidVaini** [comment]
@aaronrodgersmoustache : put target="_self" on the anchor links this will fix your problem.

Developers:
The problem is that React Router uses the hashtags for routing, I've been looking into a way to change this, the recommended approach is to use the Link component as it handles the anchor tags accordingly, however Tim's problem is anchor tags that are dynamically loaded in via dangerouslySetInnerHTML so he cant use the Link component. People have mentioned adding target="_self" to the <a> tag to get around this issue, however I think there should be a better way to handle the routing without refreshing the page and not have to add the target to the link.

**Comment by aaronrodgersmoustache** [comment]
I tried changing the target from _blank to _self and it still reloads the page.
