### ISSUE TITLE
No 4" Oval Side Bar Wheel-to-Wheel Available in Look Up Results

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#174]
Can't find any W2W parts in look up.
![image](https://cloud.githubusercontent.com/assets/11978902/17261930/031fb4ca-559e-11e6-81b0-662eeeb86939.png)

Data is populated in Godzilla
![image](https://cloud.githubusercontent.com/assets/11978902/17261936/0b45ef20-559e-11e6-8e40-e345fc792f8b.png)

**Comment by ninnemana** [comment]
Lies, they show up, they just don't have a Wheel to Wheel category.

**Comment by ninnemana** [comment]
364049, shows up under 4 IN Oval Side Bars when you look up a [2016 Chevrolet Silverado 1500](http://www.ariesautomotive.com/vehicle/2016/CHEVROLET/SILVERADO%201500). It shows up under 4 IN Oval Side Bars because that's how it is categorized in the admin: http://admin.curtmfg.com/product/1231121544/categories

**Comment by ninnemana** [comment]
The dropdown that you choose in the upload to godzilla no longer has any impact on how the tabs are displayed. The name of the tabs are completely driven by product categories.
