### ISSUE TITLE
Jeep Modular Bumper App Guide 

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#224]
I want to modify the link for the Jeep Modular Bumper App Guide so it doesn't load the Grille Guard App Guide.
![image](https://cloud.githubusercontent.com/assets/11978902/19807507/08550712-9ce6-11e6-80ba-6ef2dfd3d366.png)

I look in the app guide section in the admin and dont see Modular Bumpers.
![image](https://cloud.githubusercontent.com/assets/11978902/19807485/eaf47fb8-9ce5-11e6-9cf8-6709bb04857f.png)

**Comment by DavidVaini** [comment]
Due to the issue with the brand selection drop down changing in the admin, the application guide group/guide was saved to the wrong brand. This drop down issue has since been fixed, however the  Application Guide will have to be recreated. Then once the guide is created, it can be added to whatever application guide group it is supposed to belong to.

**Comment by ninnemana** [comment]
Can't you just update the brandID for them in MySQL? Isn't ARIES the only brand with App Guides?

**Comment by DavidVaini** [comment]
thought it was deleted, but I guess not, I switched the brand to 3, it now shows up under jeep.

**Comment by DavidVaini** [comment]
looks like @baseigneurie  latest commit broke app guides, I will fix it:
https://github.com/aries-auto/ariesautomotive/compare/db64f54f432e...773a27e1a485

**Comment by DavidVaini** [comment]
fixed with this commit:
https://github.com/aries-auto/ariesautomotive/commit/c31fa2e01f8a6604ed8340a1115e0c192c791047
