### ISSUE TITLE
Can't Paginate past 2nd page

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#229]
The applications guides pagination isn't allowing you to go past the 2nd page of results.

http://www.ariesautomotive.com/appguides/StyleGuard%20Floor%20Liners

**Comment by DavidVaini** [comment]
The Issue was a hard limit on the API side. The provided limit on the front end was higher than the hard limit on the API. This caused an unexpected number of pages. You would say a limit of 500 but only 100 results (the hard limit) would be returned which caused a mis-match. The limit provided from the front end can be anything lower or equal to the hard limit.

fixed with this commit:
https://github.com/aries-auto/ariesautomotive/commit/cbb417195a0dd593fbd4b505141dec3e00ded6d0
