### ISSUE TITLE
Async Re-fetch in Header

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#235]
Someplace in a source/store there's a local check that's failing, or we're not waiting properly for something and it's triggering a re-render of content/API calls when client is available.

Luverne Menu with JS:
![image](https://cloud.githubusercontent.com/assets/187030/20419117/880faca8-ad19-11e6-836b-2e7d17849325.png)

Luverne Menu without JS:
![image](https://cloud.githubusercontent.com/assets/187030/20419125/997733da-ad19-11e6-969e-3ed67592f0e9.png)

Likely a cached difference on the client.

**Comment by WileESpaghetti** [comment]
Steps to reproduce:

1. refresh the page and scroll down using the down arrow key or clicking on the scroll bar

Expected behavior:
The page will stay where I have scrolled to

Actual behavior:
After the page loads completely, the page will jump back to the top of the page. (The same way the site behaves when JavaScript is disabled
