### ISSUE TITLE
Dealer Locator not working

### ISSUE THREAD

**Issue by dgallegos** [aries-auto/ariesautomotive#250]
According to an email from Paul McGinley the Aries Dealer Locator hasn't been working for the past month.

**Comment by WileESpaghetti** [comment]
Steps to reproduce:

1. Go to the [Where to buy](http://www.ariesautomotive.com/buy) page
2. Wait for the page to fully load

Expected Outcome:
Error messages displayed below the search box are because of API issues, not because of JavaScript exceptions.

Actual Outcome:
A JavaScript exception occurs and displays An error message below the search box: `Cannot read property 'length' of undefined`

![Dealer Locator Error: Cannot read property 'length' of undefined](https://cloud.githubusercontent.com/assets/2218608/21237292/f016eeb4-c2c3-11e6-85e5-8d26bdba1d09.png)
