### ISSUE TITLE
ARIES Look Up Populating Part Duplicates

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#263]
When you look a 2016 Chevrolet Silverado 2500 HD. And you look at 6" Ovals. The results are being duplicated 4 times.
![image](https://cloud.githubusercontent.com/assets/11978902/22427579/5cb2c5a6-e6c9-11e6-87e5-3bdabced287f.png)

The data isn't duplicated in the godzilla database from what i can see.
![image](https://cloud.githubusercontent.com/assets/11978902/22427615/7d89d88c-e6c9-11e6-817d-47cce8d1fa3f.png)

**Comment by dgallegos** [comment]
I'm on it.

**Comment by mcrandell** [comment]
@dgallegos looks like the replication is also on the part page for a parts application data:
![image](https://cloud.githubusercontent.com/assets/11978902/22472058/1b521f36-e79a-11e6-9d95-44b443480cfe.png)

Parts brought to my attention: 4084, 4084-2, P4084

**Comment by dgallegos** [comment]
@mcrandell, I verified the parts are fixed. I'm not sure where that link is to the application guides. Can you send me a link to those application guides.

**Comment by mcrandell** [comment]
@dgallegos the duplicates were removed on my end. I asked Jesse Bauer in Product Management to look as well. Once he confirms we can close the ticket.

**Comment by mcrandell** [comment]
@dgallegos Jesse Bauer confirmed issue is resolved. 
I'm closing this ticket.

**Comment by DavidVaini** [comment]
The problem was in the IAPI endpoint for importing app data from the Product Desk CSV. The endpoint was taking longer than 30 seconds (expected) and Nginx was timing the response out and trying it again after 30 seconds. This would cause an overlap and duplicate processes from running. Traditionally any process that took longer than 15 seconds we would wrap in a go-routine so it would not block and would come back with a response. This was not the case for this endpoint so I implemented it and it fixed the duplication issue.

There is still a low risk of that endpoint could be called multiple times by us Developers, and I will create a separate issue for that problem.

**Comment by dgallegos** [comment]
http://ariesautomotive.com/vehicle/2008/JEEP/WRANGLER 

This appears to still be occurring. Check all products under "Modular Bumpers"

**Comment by DavidVaini** [comment]
the duplicates have been removed. Still investigating any potential causes for this.

**Comment by DavidVaini** [comment]
Update: The cause was the App Import was running multiple times due to a retry policy. We still want this expected behavior so I instead added a logger that logs every app data import and its progress. It stores that information in MongoDB. It also prevents the App Data import process from running multiple times in a 6 hour time period. This prevents future duplicates cause from the import process.
